#!/bin/sh
#                                                                      
# GPL3 License                                                                         
#                                                                      
#                                                                      
# Copyright (c) 2022 Ransome CA                              
#                                                                      
# This file is part of SCIARA-fv2-CUDA.                                          
#                                                                      
# SCIARA-fv2-CUDA is free software: you can redistribute it and/or modify        
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, or    
# (at your option) any later version.                                  
#                                                                      
# SCIARA-fv2-CUDA is distributed in the hope that it will be useful,             
# but WITHOUT ANY WARRANTY; without even the implied warranty of       
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        
# GNU General Public License for more details.                         
#                                                                      
# You should have received a copy of the GNU General Public License    
# along with SCIARA-fv2-CUDA.  If not, see <http://www.gnu.org/licenses/>.       
#     
#

(ssh user30@160.97.63.93 /bin/cat /home/user30/sciara-fv2-cuda/data/2006/output_2006_000000016000_$1.stt) > /tmp/graph.stt
utils/plot_stt.py /tmp/graph.stt &